# Generated by Django 4.1.4 on 2024-08-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_urldb_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldb',
            name='short_url',
            field=models.CharField(max_length=30),
        ),
    ]
